function [fitresult, gof] = fitMSDdynAndStError(x, y,n,kCycle)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Sep-2022 17:54:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

deltaTE = num2str(kCycle);
nStr = num2str(n);
term1=strcat('a*x^(2+b)*((',nStr,'-',deltaTE,'/x)^(2+b)-2*',nStr,'^(2+b)+(',nStr,'+',deltaTE,'/x)^(2+b))/((1+b)*(2+b)*',deltaTE,'^2)');
%term1= strcat('a*x^(2+b)*((1-',deltaTE,'/x)^(2+b)-2+(1+',deltaTE,'/x)^(2+b))/((1+b)*(2+b)*',deltaTE,'^2)')
term2=strcat('-2*a*',deltaTE,'^b/((1+b)*(2+b))');
term3='+c';



% Set up fittype and options.
ft = fittype( strcat(term1,term2,term3), 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.StartPoint = [2.174e+05 0.7 5000];
opts.Upper = [Inf 1 Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
hold on
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
grid on


